Attempt to fix problems with mprime-phc-setup.

diff --git a/mprime-phc-setup b/mprime-phc-setup
--- a/mprime-phc-setup
+++ b/mprime-phc-setup
@@ -22,7 +22,7 @@ long_test_length=320
 # - use 1 only if long_test_length >= 3600
 safety_vid_delta=2
 
-debug=0
+debug=1
 
 #####################################
 
@@ -75,21 +75,6 @@ echo "You can stop the test at any time with CTRL-C."
 echo "Press RETURN to go on or CTRL-C to cancel."
 read
 
-# Store stuff to be able to cleanup later
-backup_governor=$(cat $cpuf/scaling_governor)
-backup_phc_vids=$(cat $cpuf/phc_vids)
-
-# Log file for mprime
-mp_log=/tmp/$(basename $0).mp
-
-# Check that current governor is ondemand
-if [[ $backup_governor != ondemand ]]; then
-	echo "Switching to the ondemand governor. $backup_governor will be restored later."
-	modprobe cpufreq_ondemand
-	echo ondemand >$cpuf/scaling_governor
-fi
-backup_scaling_max_freq=$(cat $cpuf/scaling_max_freq)
-
 function set_sys_val
 {
 	#echo Writing $2 to $1
@@ -98,20 +83,53 @@ function set_sys_val
 	done
 }
 
+function debug_info
+{
+	for i in /sys/devices/system/cpu/cpu*/cpufreq/{scaling_governor,cpuinfo_cur_freq,scaling_cur_freq,phc_vids}; do
+		echo -n $i | sed 's/\/sys\/devices\/system\/cpu\///'
+		echo " = $(cat $i)"
+	done
+}
+
+# Store stuff to be able to cleanup later
+backup_governor=$(cat $cpuf/scaling_governor)
+backup_phc_vids=$(cat $cpuf/phc_vids)
+
+#if [[ $backup_governor != userspace ]]; then
+	echo "Switching to the userspace governor. $backup_governor will be restored later."
+	modprobe cpufreq_userspace
+	set_sys_val scaling_governor userspace
+#fi
+
+# Log file for mprime
+mp_log=/tmp/$(basename $0).mp
+
+# process ID of mprime
+mp_pid=-1
+
+function launch_mprime
+{
+	$mp &>$mp_log &
+	mp_pid=$!
+}
+
+function kill_mprime
+{
+	(( mp_pid <= 1 )) && return
+	kill $mp_pid
+	wait $mp_pid &>/dev/null # needed to suppress the "killed" message by bash
+	mp_pid=-1
+}
+
 function cleanup
 {
 	echo ""
 	echo "Restoring state…"
 
-	# Kill mprime?
-	# bash will kill it because the process hasn’t been disowned.
-	# The only problem is it might write to the log after it has been deleted.
+	kill_mprime
 
 	# Restore vids
 	set_sys_val phc_vids "$backup_phc_vids"
-
-	# Restore max frequency
-	set_sys_val scaling_max_freq "$backup_scaling_max_freq"
 
 	# Restore governor
 	set_sys_val scaling_governor "$backup_governor"
@@ -121,7 +139,7 @@ function cleanup
 }
 
 # Restore original state whenever the script exits
-trap "cleanup" EXIT
+trap cleanup EXIT
 
 # List all vids and frequencies
 freqs=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_frequencies)
@@ -181,6 +199,7 @@ echo -n " and "
 print_time estimate_max
 echo ""
 
+
 # For each available frequency, try to lower the vid as much as possible
 
 # 1st pass: Lower the vid, test mprime for a small amount of time at each step.
@@ -190,7 +209,6 @@ echo ""
 #           If there is an error, increment cur_vid and loop.
 #           Stop when there is no error or cur_vid >= max_vid-delta.
 # Final step: best_vid=cur_vid+delta
-
 
 # set_vid index vid
 function set_vid
@@ -209,33 +227,11 @@ function set_vid
 	set_sys_val phc_vids "$v"
 }
 
-function launch_mprime
-{
-	$mp &>$mp_log &
-	mp_pid=$!
-}
-
-function kill_mprime
-{
-	kill $mp_pid
-	wait $mp_pid &>/dev/null # needed to suppress the "killed" message by bash
-}
-
 cur_vid=${vid[0]}
 
 for (( f=0; f<nb_freqs; f++ )); do
 	echo ""
 	echo "Testing frequency $f (${freq[f]})…"
-
-	set_sys_val scaling_max_freq ${freq[f]}
-
-	if ((debug)); then
-		echo -n "Max freq: "
-		cat $cpuf/scaling_max_freq
-		echo -n "Current freq: "
-		cat $cpuf/cpuinfo_cur_freq
-	fi
-
 	echo "Default vid: ${vid[f]}"
 
 	# Pass 1: lowering vid quickly until there is an error
@@ -247,36 +243,39 @@ for (( f=0; f<nb_freqs; f++ )); do
 	((cur_vid--))
 
 	for (( ; cur_vid > 0; cur_vid-- )); do
-		#count=$(( short_test_length + 10 * ( ${vid[f]} + 1 - cur_vid ) / ( ${vid[f]}+1 ) ))
 		count=$short_test_length
 
 		echo "Trying vid $cur_vid for $count seconds"
 
 		set_vid $f $cur_vid
 
+		# It looks like changing the VID also resets the frequency, so set frequency here
+		set_sys_val scaling_setspeed ${freq[f]}
+
 		launch_mprime
 
 		if ((debug)); then
-			echo -n "Current vids: "
-			cat $cpuf/phc_vids
-			echo -n "Current freq: "
-			cat $cpuf/cpuinfo_cur_freq
+			sleep 1
+			debug_info
 		fi
 
 		for (( ; count>0; count-- )); do
 			sleep 1
 			echo -n "."
 			grep FATAL $mp_log &>/dev/null
-			if (( $? == 0 )); then
+			#if (( $? == 0 )); then
+			if (( cur_vid == 18 )); then	# TEST TO REMOVE #############################
 				echo ""
 				echo "Hardware failure detected."
 				((cur_vid++))
 				kill_mprime
 				break 2
 			fi
-			if (( $(cat $cpuf/cpuinfo_cur_freq) != ${freq[f]} )); then
+			cur_freq=$(cat $cpuf/scaling_cur_freq)
+			if (( ${cur_freq} != ${freq[f]} )); then
 				echo ""
-				echo "ERROR: Wrong frequency! Is scaling_max_freq ignored?"
+				echo "ERROR: Wrong frequency! (${cur_freq} instead of ${freq[f]})"
+				debug_info
 				exit 1
 			fi
 		done
@@ -293,14 +292,12 @@ for (( f=0; f<nb_freqs; f++ )); do
 		echo "Trying vid $cur_vid for $count seconds"
 
 		set_vid $f $cur_vid
+		set_sys_val scaling_setspeed ${freq[f]}
 
 		launch_mprime
 
 		if ((debug)); then
-			echo -n "Current vids: "
-			cat $cpuf/phc_vids
-			echo -n "Current freq: "
-			cat $cpuf/cpuinfo_cur_freq
+			debug_info
 		fi
 
 		for (( ; count>0; count-- )); do
@@ -340,9 +337,9 @@ echo "Final vids:   $final_vids"
 echo ""
 if [[ -e /etc/conf.d/phc-intel ]]; then
 	echo "Edit /etc/conf.d/phc-intel to add your final vids,"
-	echo "then type: sudo rc.d start phc-intel"
+	echo "then you can start the phc service."
 else
-	echo "Add the following 3 lines to /etc/rc.local, before the final \"exit 0\":"
+	echo "If your system has a working rc.local (probably not the case with systemd), you can add the following 3 lines to /etc/rc.local, before the final \"exit 0\":"
 	echo ""
 	echo "for i in /sys/devices/system/cpu/cpu*/cpufreq/phc_vids; do"
 	echo "  echo \"$final_vids\" > \$i"
